///*
// * This Java source file was generated by the Gradle 'init' task.
// */
//package com.neev.poorna;
//
//import org.junit.jupiter.api.Test;
//
//class AppTest {
//    @Test void appHasAGreeting() {
//        TryProcessing classUnderTest = new TryProcessing();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//    }
//}
